version: '3'

services:

  node:
    container_name: nodejs
    build: 
      context: ./node
    image: lordmass/nodejs-desafio-fullcycle
    restart: always
    volumes:
      - ./node:/home/node/app
    ports:
      - 3000:3000
    networks:
      - desafio-network
    command: sh -c "npm install && nodemon index.js"

networks:
  desafio-network:
    driver: bridge
    